### ISSUE TITLE
ValidReff is wrong for at least one text

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Ahab#16]
``` xml
<CTS:urn>urn:cts:greekLit:tlg0003.tlg001.perseus-grc1:1.1</CTS:urn>
<CTS:urn>urn:cts:greekLit:tlg0003.tlg001.perseus-grc1:1.2</CTS:urn>
<CTS:urn>urn:cts:greekLit:tlg0003.tlg001.perseus-grc1:1.3</CTS:urn>
<CTS:urn>urn:cts:greekLit:tlg0003.tlg001.perseus-grc1:1.4</CTS:urn>
<CTS:urn>urn:cts:greekLit:tlg0003.tlg001.perseus-grc1:1.145</CTS:urn>
<CTS:urn>urn:cts:greekLit:tlg0003.tlg001.perseus-grc1:1.1</CTS:urn>
<CTS:urn>urn:cts:greekLit:tlg0003.tlg001.perseus-grc1:1.146</CTS:urn>
<CTS:urn>urn:cts:greekLit:tlg0003.tlg001.perseus-grc1:1.1</CTS:urn>
```

**Comment by PonteIneptique** [comment]
Seems to do that only for the Thucydides I have had

**Comment by PonteIneptique** [comment]
It works ok for Cicero, Martial, Juvenal...
Trying to test another greek. No idea why it's happening

**Comment by balmas** [comment]
is it possible this is not a greek vs latin thing but a problem with reuse of the same element for each citation level? Ovid and Martial are both div/l but Thuc was div/div/div .. I noticed that the $masterPath variable in cts-common:fake-match-document contained only the last path element for each cached urn except for the very first. When I changed Thuc to div/div2/div3 the problem was "resolved" -- i.e. the validReffs returned were right (but I only tested with a version with 2 chapters)

**Comment by PonteIneptique** [comment]
Hmpf, I was quite sure about Latin / Greek. But thank you for the debugging. Looking for it in the code :)

**Comment by PonteIneptique** [comment]
This was this [crappy line](https://github.com/Capitains/CTS5-XQ/blob/master/modules/cts-common.xql#L40), found out this morning

``` xquery
let $masters := util:eval("$body/" || $masterPath, true())
```

As I go in lower level, $body becomes the div and $masterPath the scope, in other terms, this becomes $body//div. Removing the / would save us

**Comment by PonteIneptique** [comment]
This show that whatever happens regarding my release, we need heavy stresstest.
